#!/bin/bash


connectSSHP22() {
#echo "connectSSH Default"
	sshpass -p "$2" ssh -p22 -o 'StrictHostKeyChecking no' $1@$3 $4
}



deviceFullReport() {


	run=$(connectSSHP22 "$1" "$2" "$3" 'echo `cat /etc/board.info | grep board.name | cut -d= -f2`+\
		`cat /etc/board.info | grep board.hwaddr | cut -d= -f2`+`cat /tmp/system.cfg | grep ppp.1.name | cut -d= -f2 | head -n 1`+\
			`cat /tmp/system.cfg | grep wireless.1.ssid | cut -d= -f2`+-`/usr/www/signal.cgi | grep signal | cut -d- -f2 | cut -c-2`')

	out=$?

echo $run

}


deviceFullReport "USER" "PASSWORD" "IP"