#!/bin/bash

name='a1b2c3d4e5f6'

count=1

for i in {3,6,9,12,15,18}; do
#	echo i=$i

	for (( j=1; j <= 2; j++ )); do
		text="$text""$(echo "$name" | cut -c $count)"
		((count++))
	done


	if [ $i -le 15 ]; then
		text="$text":
	fi

#	echo $text

done


printf "MAC sem formatação:\t$name\n"
printf "MAC formatado:\t\t$text\n"

stext=$(echo $text | tr [:lower:] [:upper:])

printf "MAC formatado (upper):\t$stext\n"
